export const HOBBIES = [
  "Woodworking",
  "Gardening",
  "Cooking",
  "Photography",
  "Playing an Instrument",
  "Knitting/Crochet",
  "Coding/Software",
  "Painting/Drawing",
  "3D Printing",
  "Hiking/Camping",
  "Sewing",
  "Pottery",
  "Home Brewing",
  "Cycling",
  "Board Games",
  "Model Building",
  "Birdwatching",
  "Yoga",
  "Fishing",
  "Baking",
];

export const ELEMENTS = [
  "Electronics",
  "Poetry",
  "Mycology",
  "Data Visualization",
  "Sewing",
  "Foraging",
  "Mapmaking",
  "Astronomy",
  "Music",
  "Geology",
  "Chemistry",
  "Blacksmithing",
  "Calligraphy",
  "Mixology",
  "Puzzle Design",
  "Local History",
  "Fermentation",
  "Kintsugi",
  "Botany",
  "Clockmaking",
  "Creative Writing",
  "Martial Arts",
  "Stargazing",
  "Urban Exploration",
  "Color Theory",
];
